version: '3'
services:
  app:
    container_name: devopstarea16deoctubre
    build: .
    ports:
      - '3000:3000'
      - '5000:5000'
    networks:
      - mi-red
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: mysqlcontainer
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: formulario
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '3307:3306'
    networks:
      mi-red:
        aliases:
          - mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5
networks:
  mi-red: